config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  get '/users/sign_out', to: 'users#user_sign_out', as: 'sign_out'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new destroy] do
      resources :comments, only: %i[destroy]
      resources :likes, only: %i[]
    end
  end
  

  get '/users/:id/posts/new', to: 'posts#new', as: 'post_new'
  post '/users/:id/posts/create', to: 'posts#create', as: 'post_create'

  get '/users/:user_id/posts/:id/comments/new', to: 'comments#new', as: 'comment_new'
  post '/users/:user_id/posts/:id/comments/create', to: 'comments#create', as: 'comment_create'

  post '/users/:user_id/posts/:id/likes/create', to: 'likes#create', as: 'like_create'

  # get '/users/:user_id/posts', to: 'posts#index', as: 'show_a_user_posts_comments'
  # get '/users/:user_id/posts/:id', to: 'posts#show', as: 'show_a_user_a_post_comments'

  root 'users#index'

  # for API
  get '/api/users', to: 'users#index_api'
  get '/api/users/:user_id/posts/:id', to: 'posts#show_api'
  
  post '/api/auth/login', to: 'authentication#login'

  namespace :api, default: {format: :json} do
    namespace :v1 do
      resources :users, only: %i[index] do
        resources :posts, only: %i[index show] do
          resources :comments, only: %i[index create]
        end
      end
    end
  end 

end

app/models/comment.rb
class Comment < ApplicationRecord
  after_save :count_comments
  belongs_to :post, foreign_key: 'post_id'
  belongs_to :user, foreign_key: 'user_id'

  def count_comments
    post = Post.find(post_id)
    post.update(comments_counter: post.comments.size)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  load_and_authorize_resource except: %i[create]
  skip_before_action :verify_authenticity_token

  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments
    render json: {
      success: true,
      data: {
        post: @post,
        comments: @comments
      }
    }
  end

  def create
    @current_user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])

    @comment = Comment.new(text: params[:text])
    @comment.user_id = @current_user.id
    @comment.post_id = @post.id

    if @comment.save
      render json: { success: true, data: { comment: @comment, user: @current_user } }, status: :created
    else
      render json: { success: false, errors: @comment.errors.full_messages }, status: :unprocessable_entity
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  before_action :set_post, only: %i[new create index_api]
  before_action :set_user, only: %i[new]

  # '/users/:user_id/posts/:id/comments/new'
  def new; end

  # '/users/:user_id/posts/:id/comments/create'
  def create
    @new_comment = Comment.new(comment_params)
    @new_comment.user_id = current_user.id
    @new_comment.post_id = @post.id

    if @new_comment.save
      flash[:notice] = 'New comment added successfully!'
      redirect_to "/users/#{@post.author_id}/posts/#{@post.id}"
    else
      render :new
    end
  end

  def destroy
    selected_comment = Comment.find(params[:id])
    return unless selected_comment.destroy

    flash[:success] = 'Comment deleted successfully!'
    redirect_to request.referer
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  
  <div class="comment-item">
    <%= User.find(comment.user_id).name %>
    :
    <%= comment.text %>

    <% if user_signed_in? %>

      <% if (can? :destroy, comment) %>
        <%= button_to "X", "/users/#{comment.user_id}/posts/#{comment.post_id}/comments/#{comment.id}", method: 'delete' %>
      <% end %>

    <% end %>

  </div>

</div>

app/views/comments/_form.html.erb
<%= form_with model: comment, url: comment_create_path(user_id: current_user.id, id: @post.id), method: 'post', local: true, scope: :comment do |form| %>

  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_area :text, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/new.html.erb
New comment
<%= render @post %>

<div class="form">
<%= render 'form', comment: @comment %>
</div>


<%= link_to 'Back', "/users/#{@post.author_id}/posts/#{@post.id}", class:"link-btn" %>