config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  get '/users/sign_out', to: 'users#user_sign_out', as: 'sign_out'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new destroy] do
      resources :comments, only: %i[destroy]
      resources :likes, only: %i[]
    end
  end
  

  get '/users/:id/posts/new', to: 'posts#new', as: 'post_new'
  post '/users/:id/posts/create', to: 'posts#create', as: 'post_create'

  get '/users/:user_id/posts/:id/comments/new', to: 'comments#new', as: 'comment_new'
  post '/users/:user_id/posts/:id/comments/create', to: 'comments#create', as: 'comment_create'

  post '/users/:user_id/posts/:id/likes/create', to: 'likes#create', as: 'like_create'

  # get '/users/:user_id/posts', to: 'posts#index', as: 'show_a_user_posts_comments'
  # get '/users/:user_id/posts/:id', to: 'posts#show', as: 'show_a_user_a_post_comments'

  root 'users#index'

  # for API
  get '/api/users', to: 'users#index_api'
  get '/api/users/:user_id/posts/:id', to: 'posts#show_api'
  
  post '/api/auth/login', to: 'authentication#login'

  namespace :api, default: {format: :json} do
    namespace :v1 do
      resources :users, only: %i[index] do
        resources :posts, only: %i[index show] do
          resources :comments, only: %i[index create]
        end
      end
    end
  end 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end

  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  has_many :comments, foreign_key: 'user_id'
  has_many :likes, foreign_key: 'user_id'
  has_many :posts, foreign_key: 'author_id'

  def recent_posts(num = 3)
    posts.order(created_at: :desc).limit(num)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  load_and_authorize_resource
  skip_before_action :verify_authenticity_token

  def index
    @users = User.all.order(:created_at)
    render json: { success: true, data: { users: @users } }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users or /users.json
  def index
    @users = User.all.order(created_at: 'desc')
  end

  def index_api
    @users = User.all.order(created_at: 'desc')
    render json: @users
  end

  # new_user_registration GET    /users/sign_up(.:format)
  def new; end

  def confirmation; end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def user_sign_out
    sign_out(current_user)
    redirect_to '/'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>" >

  <div class="user_item" >
    <p>
    <% if !user.photo.strip.empty? %>
      <img src="<%= user.photo %>" class="user_photo" alt="<%= user.photo %>" />
    <% else %>
      <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_640.png" class="user_photo" alt="user avatar" />
    <% end %>
    </p>
    
    
    <p>
      <strong>Name:</strong>
      <%= user.name %>
    </p>


    <p>
      <strong>Posts counter:</strong>
      <%= user.posts_counter %>
    </p>

  </div>


  <% if !@posts.nil? && !url_for.include?('post') %>
    <p class="bio">
      <strong><%= user.name%>'s Bio:</strong>
      <%= "#{user.bio}. " * 3 %>
    </p>

    
    <%= render user.recent_posts(3)  %>
    
  <% end %>
  
</div>

  

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<header>
  <h2>All users</h2>
  
  <% if user_signed_in? %>
    <%= button_to 'New post', post_new_path(id: current_user.id), method: 'get', class: 'link-btn' %>
  <% end %>
  

<header>
<div id="users">
  <% @users.each do |user| %>
    <%= link_to "/users/#{user.id}" do %>
      
      <%= render user %>

    <% end %>
  <% end %>
</div>

<%# <%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form" %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<h2>Recent Posts</h2>

<%= render @user %>

<div class="bottom">
  <%# <%= link_to "Edit this user", edit_user_path(@user) %>
  <p>
    <strong><%= link_to "Back to users", users_path %></strong>
  </p>

  <p>
    <strong>
    <%= link_to "SHOW ALL POSTS", "/users/#{@user.id}/posts" %>
    </strong>
  </p>
  <%# <%= button_to "Destroy this user", @user, method: :delete %>
</div>