config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  get '/users/sign_out', to: 'users#user_sign_out', as: 'sign_out'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new destroy] do
      resources :comments, only: %i[destroy]
      resources :likes, only: %i[]
    end
  end
  

  get '/users/:id/posts/new', to: 'posts#new', as: 'post_new'
  post '/users/:id/posts/create', to: 'posts#create', as: 'post_create'

  get '/users/:user_id/posts/:id/comments/new', to: 'comments#new', as: 'comment_new'
  post '/users/:user_id/posts/:id/comments/create', to: 'comments#create', as: 'comment_create'

  post '/users/:user_id/posts/:id/likes/create', to: 'likes#create', as: 'like_create'

  # get '/users/:user_id/posts', to: 'posts#index', as: 'show_a_user_posts_comments'
  # get '/users/:user_id/posts/:id', to: 'posts#show', as: 'show_a_user_a_post_comments'

  root 'users#index'

  # for API
  get '/api/users', to: 'users#index_api'
  get '/api/users/:user_id/posts/:id', to: 'posts#show_api'
  
  post '/api/auth/login', to: 'authentication#login'

  namespace :api, default: {format: :json} do
    namespace :v1 do
      resources :users, only: %i[index] do
        resources :posts, only: %i[index show] do
          resources :comments, only: %i[index create]
        end
      end
    end
  end 

end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  has_many :comments, foreign_key: 'post_id', dependent: :destroy
  has_many :likes, foreign_key: 'post_id', dependent: :destroy

  belongs_to :user, foreign_key: 'author_id', counter_cache: 'posts_counter'

  def recent_comments(num = 5)
    comments.order(created_at: :desc).limit(num)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = Post.all.order('created_at')
    render json: { success: true, data: { posts: @posts } }, status: :ok
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  # before_action :authenticate_user!, only: %i[create destroy]

  before_action :set_user, only: %i[show index destroy]
  before_action :set_post, only: %i[show destroy]

  # # GET /posts or /posts.json
  def index
    @posts = @user.posts.includes(:comments).order(created_at: 'desc')
  end

  # # GET /posts/1 or /posts/1.json
  def show; end

  def new; end

  def create
    @new_post = Post.new(post_params)
    @new_post.author_id = current_user.id

    if @new_post.save
      flash[:success] = 'Post created successfully!'
      redirect_to "/users/#{@new_post.author_id}"
    else
      render :new, alert: 'Failed to like the post.'
    end
  end

  def destroy
    selected_post = Post.find(params[:id])
    return unless selected_post.destroy

    flash[:notice] = 'Post deleted successfully'
    redirect_to request.referer
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:user_id])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: post, url: post_create_path(id: current_user.id), method: 'post', local: true, scope: :post do |form| %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text, required: true %>
  </div>

  <div>
    <%= form.submit "Add" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="post-item">
<%= link_to "/users/#{@user.id}/posts/#{post.id}" do %>

  <h3>
    <strong>Post:</strong>
    <%= post.title %>
    (<%= @user.name %>)

  </h3>

  <p>
    <% if url_for.match(/posts\//) %>
      <%= "#{post.text}. " * 30 %>
    <% else %>
      <%= "#{post.text}. " * 10 %>
    <% end %>  
  </p>

<% end %>


  <div class="comments-container">
  <% if url_for.match(/posts/) %>
    <% if url_for.match(/posts\//) %>
    
        <% post.comments.each do |comment| %>
          <%= render comment %>
        <% end %>

      <% else %>
        <% post.comments.each_with_index do |comment, index| %>
          <% if index < 5 %>
            <%= render comment %>
          <% end %>
        <% end %>


    <% end %>  
  <% end %>
  </div>

  <div class="comment-like-bottom">
    
    <% if user_signed_in? %>
      
      <% if (can? :destroy, post) %>
        <%= button_to "delete", "/users/#{@user.id}/posts/#{post.id}", method: 'delete' %>
      
      <% end %>


      <%= button_to 'New comment', comment_new_path(user_id: post.author_id, id: post.id), method: 'get', class: 'link-btn' %>

      <strong>Comments:
        <%= post.comments_counter %>
      </strong>

      

      <%= button_to "#{post.likes_counter} likes", like_create_path(user_id: post.author_id, id: post.id), method: 'post' %>

    <% end %>



  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recent Comments</h1>
<h2>
  <%= link_to 'Home', users_path %>
</h2>


<div id="posts">
  
  <%= render @user %>

  <% @posts.each do |post| %>
      
      <%= render "post", post: post %>
    
  <% end %>
</div>

<div class="bottom">
  <strong>
  <%= link_to "Back to all posts", "/users/#{@user.id}" %>
  </strong>
</div>
<%# <%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

All Comments
<%= render @post %>


<div class="bottom">
  <strong>
  <%= link_to "Back to posts", "/users/#{@user.id}/posts" %>
  </strong>
  <%# <%= button_to "Destroy this post", @post, method: :delete %>
</div>